#!/bin/bash

OPENSOURCE=$HOME/Codes/Open/
# Add the current directory in the PATH
PATH=$PATH:.
PATH=$PATH:./node_modules/.bin/

# PATH for golang packages
GOPATH=$HOME/.golang
PATH=$PATH:${GOPATH}/bin
export GOPATH

# PATH for gems with rbenv 
PATH=$HOME/.rbenv/bin:$PATH 
GEM_HOME=$(ruby -e 'print Gem.user_dir')
PATH=$PATH:$GEM_HOME/bin

#PATH for python packages installed by pip --user  without sudo
PY_BIN=$(python -c 'import site; print(site.USER_BASE + "/bin")')
PATH=$PATH:$PY_BIN
PIP_CONFIG_FILE=$HOMR/.pip.conf


# PATH for global node packages directory 
NVM_DIR=$HOME/.dotfiles/nvm
# PATH=$PATH:`yarn global bin --offline`
# NPM_CONFIG_PREFIX=~/.npm-packages
# NPM_PACKAGES="${HOME}/.npm-packages"
# NODE_PATH=${NODE_PATH}:${NPM_PACKAGES}/lib/node_modules
# PATH=$PATH:${NPM_PACKAGES}/bin

# Android tools
PATH=$PATH:/opt/android-sdk/tools/
PATH=$PATH:/opt/android-sdk/tools/bin/
export ANDROID_HOME=/opt/android-sdk

# Java
JAVA_HOME=/usr/lib/jvm/java-8-openjdk
PATH=$PATH:$JAVA_HOME/bin

# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH 
# Delete if you already modified MANPATH elsewhere in your config
MANPATH=${NPM_PACKAGES}/share/man:$(manpath)

# Personal Apps
PATH=$PATH:$HOME/Bin

# Assume the terminal supports 256 colours
# export TERM="screen-256color"
# vim as default
export EDITOR="nvim"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Prefer French and use UTF-8
export LC_ALL="fr_FR.UTF-8"
export LANG="fr_FR"

# Use standard ISO 8601 timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
export HISTTIMEFORMAT='%F %T '

# keep history up to date, across sessions, in realtime
#  http://unix.stackexchange.com/a/48113
export HISTCONTROL="erasedups:ignoreboth"       # no duplicate entries
export HISTSIZE=100000                          # big big history (default is 500)
export HISTFILESIZE=$HISTSIZE                   # big big history
# Don't record some commands
HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:which:b:c:clear:cd:z" # for bash

# Proxy
# export http_proxy="http://localhost:3128/" 
# export HTTP_PROXY=$http_proxy 

# Compilation flags
# export ARCHFLAGS="-arch x86_64"


# Enable colors for ls, etc.  Prefer ~/.dir_colors #64489
if type -p dircolors >/dev/null ; then
	if [[ -f ~/.dir_colors ]] ; then
		eval $(dircolors -b ~/.dir_colors)
	elif [[ -f /etc/DIR_COLORS ]] ; then
		eval $(dircolors -b /etc/DIR_COLORS)
	fi
fi
